services:
  # EMQX MQTT Broker
  emqx:
    image: emqx/emqx:5.3.2
    container_name: esp32_emqx
    ports:
      - "1883:1883"      # MQTT
      - "8083:8083"      # WebSocket
      - "8084:8084"      # WSS
      - "8883:8883"      # MQTTS
      - "18083:18083"    # Dashboard
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=0.0.0.0
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - iot_network

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: esp32_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - iot_network

  # Django Application
  django_app:
    build: .
    container_name: esp32_django
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # MongoDB Configuration (using local Docker service)
      MONGODB_URI: "mongodb://admin:adminpassword@mongodb:27017/"
      MONGODB_DB_NAME: "esp32_iot_data"
 
      # MQTT Configuration (using local Docker service)
      MQTT_BROKER_HOST: "emqx"
      MQTT_BROKER_PORT: 1883
 
      # OpenWeather API Configuration
      OPENWEATHER_CITY: "Bizerte"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - iot_network
    restart: unless-stopped

volumes:
  emqx_data:
  emqx_log:
  mongodb_data:

networks:
  iot_network:
    driver: bridge